// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkVsklaaY60C_QokHJS92_GrsJysVDrI',
    appId: '1:737457960695:web:9a080815d82f94d05805f2',
    messagingSenderId: '737457960695',
    projectId: 'efeotegadev',
    authDomain: 'efeotegadev.firebaseapp.com',
    storageBucket: 'efeotegadev.appspot.com',
    measurementId: 'G-NFBNFMTLYB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Tao8ngxUp4IAMC1dFUFP-n0u3nOTJ3g',
    appId: '1:737457960695:ios:f55dec8862ed6b275805f2',
    messagingSenderId: '737457960695',
    projectId: 'efeotegadev',
    storageBucket: 'efeotegadev.appspot.com',
    iosBundleId: 'com.nerdyapps.ggSmsPool',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Tao8ngxUp4IAMC1dFUFP-n0u3nOTJ3g',
    appId: '1:737457960695:ios:f55dec8862ed6b275805f2',
    messagingSenderId: '737457960695',
    projectId: 'efeotegadev',
    storageBucket: 'efeotegadev.appspot.com',
    iosBundleId: 'com.nerdyapps.ggSmsPool',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgnBdNbyH5Bw4ImTJP3Jk2m7MkydRrhs',
    appId: '1:737457960695:android:517543e642a38e825805f2',
    messagingSenderId: '737457960695',
    projectId: 'efeotegadev',
    storageBucket: 'efeotegadev.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIkVsklaaY60C_QokHJS92_GrsJysVDrI',
    appId: '1:737457960695:web:23bfb66e0d592e635805f2',
    messagingSenderId: '737457960695',
    projectId: 'efeotegadev',
    authDomain: 'efeotegadev.firebaseapp.com',
    storageBucket: 'efeotegadev.appspot.com',
    measurementId: 'G-SJHBLBZFJ7',
  );

}